# Generated by Django 5.1.6 on 2025-02-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_userprofile_regno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log_Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address_used", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now=True)),
                ("deviced_used", models.CharField(max_length=20)),
                ("website_visited", models.URLField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="portal.userprofile",
                    ),
                ),
            ],
        ),
    ]
