# Generated by Django 5.1.6 on 2025-02-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_log_usage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log_usage",
            old_name="deviced_used",
            new_name="device_used",
        ),
    ]
