# Generated by Django 5.1.6 on 2025-02-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_rename_deviced_used_log_usage_device_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log_usage",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
